### PR TITLE
Improve flattening

### PR DESCRIPTION
**Pull request by d-m-bailey**

### CODE REVIEW

**Comment by d-m-bailey** [comment]
@lankasaicharan Any idea why the CI check is failing?

**Comment by lankasaicharan** [comment]
> @lankasaicharan Any idea why the CI check is failing?

@d-m-bailey its the 5th testcase which is failing. I am attaching the log file of it. 
[vezzal_fail.log](https://github.com/RTimothyEdwards/netgen/files/7795925/vezzal_fail.log)

**Comment by d-m-bailey** [comment]
@lankasaicharan Ok, so it's not necessarily a failure caused by my changes, right? 

The netB.spice looks like it's missing devices inside subcircuits.
```
Contents of circuit 2:  Circuit: 'sky130_fd_sc_hvl__inv_8'
Circuit sky130_fd_sc_hvl__inv_8 contains 0 device instances.
Circuit contains 0 nets.
```

The current version of netgen does not flatten a circuit if the corresponding circuit does not contain any devices.

**Comment by lankasaicharan** [comment]
> 

Right.

**Comment by RTimothyEdwards** [comment]
I'll check this today.  The original intent (sometime way back) was that the "-blackbox" option would control the behavior with respect to empty subcells.  I don't think it is workable to hard-code it one way or the other.  But I think that right now, the "-blackbox" option, while parsed, doesn't do anything meaningful.

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me (the original code must have had a long debugging history to have become so convoluted).  Great improvement.

**Comment by RTimothyEdwards** [comment]
I ended up merging this one manually, but it's been done.

**Pull request closed without merging**
